apiVersion: apps/v1
kind: Deployment
metadata:
  name: demostration
spec:
  replicas: 3
  selector:
    matchLabels:
      role: hello
  template:
    metadata:
      labels:
        role: hello
    spec:
      containers:
      - name: demo
        image: marianoal/demostration:1.0
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000 #que puerto se cree en cada nodo para llegar al svc.
  selector:
    role: hello
